import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    // alignItems: 'center'
  },
  flexTitle: {
    flexDirection: 'row',
    marginBottom: 20,
    paddingTop: 10,
    padding: 5,
    // justifyContent: 'space-evenly',
    // alignItems: 'center',
  },
  flexformContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    paddingTop: 10,
    padding: 5,
    paddingRight: 10,
    flexWrap: 'wrap',
  },
  formContainer: {
    marginTop: 20,
    // flex: 1,
    paddingLeft: 30,
    paddingRight: 30,
  },
  input: {
    height: 40,
    margin: 15,
    borderWidth: 1,
    padding: 10,
  },
  footerButton: {
    height: 47,
    padding: 5,
    margin: 12,
    borderRadius: 5,
    backgroundColor: '#f89b1d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    height: 47,
    padding: 10,
    margin: 12,
    borderRadius: 5,
    backgroundColor: '#f89b1d',
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  updateButton: {
    height: 47,
    borderRadius: 5,
    backgroundColor: '#f89b1d',
    width: 80,
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    height: 47,
    borderRadius: 5,
    backgroundColor: '#FF0000',
    width: 80,
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  DisabledButton: {
    height: 47,
    borderRadius: 5,
    backgroundColor: '#D3D3D3',
    width: 80,
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  LOGOUT: {
    color: 'black',
    fontSize: 16,
    padding: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
  },
  doneText: {
    color: '#00FF00',
    fontSize: 16,
  },
  listContainer: {
    flex: 1,
    marginBottom: 10,
  },
  entityContainer: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 5,
    flex: 1,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 10,
    shadowOpacity: 0.26,
    elevation: 8,
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
  },
  entityText: {
    fontSize: 16,
    padding: 10,
    paddingTop: 8,
    color: '#333333',
  },
  checkbox: {
    textAlign: 'right',
    alignSelf: 'flex-end',
    marginLeft:'auto'
  },
  titleText: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  titleUpdate: {
    height: 40,
    fontSize: 20,
    fontWeight: 'bold',
    borderWidth: 1,
    padding: 10,
  },
})
